name: Check Tailscale latest release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch latest release tag
        id: fetch-tag
        run: |
          tag=$(curl -sL https://api.github.com/repos/tailscale/tailscale/releases/latest | \
          jq -r ".tag_name")
          echo $tag > tailscale-version.txt
          echo ::set-output name=tag::$tag
      - name: Check modified
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit new version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'check-tailscale-release'
          git config --global user.email '<>'
          git commit -am "${{ steps.fetch-tag.outputs.tag }}"
          git push

# https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release